// AI News 同步配置
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const CONFIG = {
  OUTPUT_PATH: path.join(__dirname, '../../src/data/ai-news.json'),
  AI_NEWS_IMAGES_DIR: path.join(__dirname, '../../public/images/ai-news'),
  AI_NEWS_IMAGES_PUBLIC_PATH: '/images/ai-news',
  USER_AGENT: 'bigroc-blog-ai-news-bot/2.0 (+https://bigroc.cn)',
  BROWSER_USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36',
  LATEST_WINDOW_HOURS: 72,
  MAX_LATEST_ITEMS: 24,
  MAX_LATEST_ITEMS_PER_SOURCE: 4,
  MIN_CN_LATEST_ITEMS: 6,
  MAX_SNAPSHOT_FETCHES_PER_RUN: 24,
  TRANSLATION_ENABLED: process.env.AI_NEWS_TRANSLATOR !== 'none',
  TRANSLATION_BASE_URL: 'https://api.mymemory.translated.net/get',
  TRANSLATION_DELAY_MS: 250,
  ARTICLE_CONTENT_MAX_CHARS: 20000,
  ARTICLE_BLOCK_MAX_COUNT: 120,
  REQUEST_TIMEOUT_MS: 8000,
};

export const SOURCES = [
  {
    id: 'openai-news',
    name: 'OpenAI News',
    homepage: 'https://openai.com/news/',
    url: 'https://openai.com/news/rss.xml',
    kind: 'rss',
    sourceType: 'official',
    sourceRegion: 'global',
    language: 'en',
    priority: 30,
  },
  {
    id: 'google-ai-blog',
    name: 'Google AI Blog',
    homepage: 'https://blog.google/technology/ai/',
    url: 'https://blog.google/technology/ai/rss/',
    kind: 'rss',
    sourceType: 'official',
    sourceRegion: 'global',
    language: 'en',
    priority: 28,
  },
  {
    id: 'google-deepmind',
    name: 'Google DeepMind',
    homepage: 'https://www.deepmind.com/blog',
    url: 'https://www.deepmind.com/blog/rss.xml',
    kind: 'rss',
    sourceType: 'official',
    sourceRegion: 'global',
    language: 'en',
    priority: 28,
  },
  {
    id: 'techcrunch-ai',
    name: 'TechCrunch AI',
    homepage: 'https://techcrunch.com/category/artificial-intelligence/',
    url: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    kind: 'rss',
    sourceType: 'media',
    sourceRegion: 'global',
    language: 'en',
    priority: 20,
  },
  {
    id: 'the-verge-ai',
    name: 'The Verge AI',
    homepage: 'https://www.theverge.com/ai-artificial-intelligence',
    url: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    kind: 'rss',
    sourceType: 'media',
    sourceRegion: 'global',
    language: 'en',
    priority: 18,
  },
  {
    id: 'venturebeat-ai',
    name: 'VentureBeat AI',
    homepage: 'https://venturebeat.com/ai/',
    url: 'https://venturebeat.com/category/ai/feed/',
    kind: 'rss',
    sourceType: 'media',
    sourceRegion: 'global',
    language: 'en',
    priority: 18,
  },
  {
    id: 'mit-tech-review-ai',
    name: 'MIT Technology Review AI',
    homepage: 'https://www.technologyreview.com/topic/artificial-intelligence/',
    url: 'https://www.technologyreview.com/feed/',
    kind: 'rss',
    sourceType: 'media',
    sourceRegion: 'global',
    language: 'en',
    priority: 16,
  },
  {
    id: 'ars-technica-ai',
    name: 'Ars Technica AI',
    homepage: 'https://arstechnica.com/ai/',
    url: 'https://arstechnica.com/feed/',
    kind: 'rss',
    sourceType: 'media',
    sourceRegion: 'global',
    language: 'en',
    priority: 16,
  },
  {
    id: 'hugging-face-blog',
    name: 'Hugging Face Blog',
    homepage: 'https://huggingface.co/blog',
    url: 'https://huggingface.co/blog/feed.xml',
    kind: 'rss',
    sourceType: 'community',
    sourceRegion: 'global',
    language: 'en',
    priority: 14,
  },
  {
    id: 'openai-blog',
    name: 'OpenAI Blog',
    homepage: 'https://openai.com/blog/',
    url: 'https://openai.com/blog/rss.xml',
    kind: 'rss',
    sourceType: 'official',
    sourceRegion: 'global',
    language: 'en',
    priority: 25,
  },
  {
    id: 'anthropic-news',
    name: 'Anthropic News',
    homepage: 'https://www.anthropic.com/news',
    url: 'https://www.anthropic.com/rss.xml',
    kind: 'rss',
    sourceType: 'official',
    sourceRegion: 'global',
    language: 'en',
    priority: 25,
  },
  {
    id: '36kr-ai',
    name: '36氪 AI',
    homepage: 'https://36kr.com/information/AI/',
    url: 'https://36kr.com/information/AI/',
    kind: 'list',
    sourceType: 'media',
    sourceRegion: 'cn',
    language: 'zh',
    priority: 22,
  },
  {
    id: 'ithome-ai',
    name: 'IT之家 AI',
    homepage: 'https://www.ithome.com/tag/AI',
    url: 'https://www.ithome.com/tag/AI',
    kind: 'list',
    sourceType: 'media',
    sourceRegion: 'cn',
    language: 'zh',
    priority: 20,
  },
  {
    id: 'qbitai',
    name: '量子位',
    homepage: 'https://www.qbitai.com/',
    url: 'https://www.qbitai.com/',
    kind: 'list',
    sourceType: 'media',
    sourceRegion: 'cn',
    language: 'zh',
    priority: 20,
  },
  {
    id: 'leiphone',
    name: '雷锋网 AI',
    homepage: 'https://www.leiphone.com/category/ai',
    url: 'https://www.leiphone.com/category/ai',
    kind: 'list',
    sourceType: 'media',
    sourceRegion: 'cn',
    language: 'zh',
    priority: 18,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    homepage: 'https://www.deepseek.com/',
    url: 'https://www.deepseek.com/',
    kind: 'list',
    sourceType: 'official',
    sourceRegion: 'cn',
    language: 'zh',
    priority: 25,
  },
];

export function defaultDigest() {
  return {
    updatedAt: new Date().toISOString(),
    windowHours: CONFIG.LATEST_WINDOW_HOURS,
    stats: {
      totalItems: 0,
      recent24h: 0,
      sources: {},
    },
    latestIds: [],
    items: [],
  };
}
